import {NextRequest,NextResponse} from 'next/server'
import {createPromotion,listPromotions,setPromotionActive,updatePromotion} from '@/lib/promotion-store'
import {updateUnusedPromotionCouponPricing} from '@/lib/promotion-coupon-store'
export const dynamic='force-dynamic'
const isAdmin=(r:NextRequest)=>Boolean(process.env.ADMIN_PASSWORD&&r.headers.get('x-admin-password')===process.env.ADMIN_PASSWORD)
type Body={id?:string;title?:string;description?:string;startAt?:string;endAt?:string;discountLabel?:string;productLabel?:string;couponEnabled?:boolean;discountRate?:number;referencePrice?:number|null;customPrice?:boolean;active?:boolean}
const validate=(b:Body)=>{if(!b.title?.trim()||!b.description?.trim()||!b.startAt||!b.endAt)return'Titre, description et dates obligatoires.';if(b.couponEnabled&&(!Number.isFinite(Number(b.discountRate))||Number(b.discountRate)<=0||Number(b.discountRate)>100))return'Le pourcentage du coupon doit être compris entre 1 et 100.';if(b.referencePrice!==null&&b.referencePrice!==undefined&&(!Number.isFinite(Number(b.referencePrice))||Number(b.referencePrice)<0))return'Le prix de référence est invalide.';return''}
const input=(b:Body)=>({title:b.title!,description:b.description!,startAt:b.startAt!,endAt:b.endAt!,discountLabel:b.discountLabel||'',productLabel:b.productLabel||'',couponEnabled:Boolean(b.couponEnabled),discountRate:b.couponEnabled?Number(b.discountRate):null,referencePrice:b.referencePrice===null||b.referencePrice===undefined?null:Number(b.referencePrice),customPrice:Boolean(b.customPrice)})
export async function GET(request:NextRequest){try{const rows=await listPromotions(!isAdmin(request));return NextResponse.json({promotions:rows})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Lecture impossible.'},{status:500})}}
export async function POST(request:NextRequest){if(!isAdmin(request))return NextResponse.json({error:'Accès refusé.'},{status:401});try{const b=await request.json()as Body;const error=validate(b);if(error)return NextResponse.json({error},{status:400});const promotion=await createPromotion(input(b));return NextResponse.json({ok:true,promotion})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Création impossible.'},{status:500})}}
export async function PATCH(request:NextRequest){if(!isAdmin(request))return NextResponse.json({error:'Accès refusé.'},{status:401});try{const b=await request.json()as Body;if(!b.id)return NextResponse.json({error:'Données invalides.'},{status:400});if(typeof b.active==='boolean'&&!b.title){await setPromotionActive(b.id,b.active);return NextResponse.json({ok:true})}const error=validate(b);if(error)return NextResponse.json({error},{status:400});const values=input(b);const promotion=await updatePromotion(b.id,values);await updateUnusedPromotionCouponPricing(b.id,values.productLabel,values.referencePrice);return NextResponse.json({ok:true,promotion})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Mise à jour impossible.'},{status:500})}}
