import { NextRequest, NextResponse } from 'next/server'
import webpush,{type PushSubscription} from 'web-push'
import { listOffersNeedingReminder, markReminderSent } from '@/lib/welcome-offer-store'
import { deletePushSubscription, listPushSubscriptions } from '@/lib/push-store'
import { normalizeContent, type SiteContent } from '@/lib/default-content'
import { pendingReopening } from '@/lib/reopening'
export const runtime='nodejs';export const dynamic='force-dynamic'

const githubSettings=()=>({token:process.env.GITHUB_TOKEN,repo:process.env.GITHUB_REPO||'thomasdubois60-svg/lebistrotducoin',branch:process.env.GITHUB_BRANCH||'main'})
const githubHeaders=(token:string)=>({Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'})
async function claimReopening(now:Date){const{token,repo,branch}=githubSettings();if(!token)return null;const url=`https://api.github.com/repos/${repo}/contents/data/site-content.json`;const current=await fetch(`${url}?ref=${encodeURIComponent(branch)}`,{headers:githubHeaders(token),cache:'no-store'});if(!current.ok)return null;const file=await current.json();const content=normalizeContent(JSON.parse(Buffer.from(file.content,'base64').toString('utf8')) as SiteContent);const window=pendingReopening(content,now);if(!window)return null;const general={...content.general,reopeningProcessedClosureEnd:content.general.closureEnd,reopeningBannerStart:content.general.reopeningBannerEnabled?window.start.toISOString():'',reopeningBannerEnd:content.general.reopeningBannerEnabled?window.end.toISOString():''};const next={...content,general};const update=await fetch(url,{method:'PUT',headers:githubHeaders(token),body:JSON.stringify({message:'Réouverture automatique du Bistrot',content:Buffer.from(JSON.stringify(next,null,2)+'\n').toString('base64'),sha:file.sha,branch}),cache:'no-store'});if(!update.ok)return null;return{general,window}}

export async function GET(request:NextRequest){const secret=process.env.CRON_SECRET;const auth=request.headers.get('authorization');if(!secret||auth!==`Bearer ${secret}`)return NextResponse.json({error:'Accès refusé.'},{status:401});const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;const privateKey=process.env.VAPID_PRIVATE_KEY;const subject=process.env.VAPID_SUBJECT||'mailto:lebistrotducoin41220@gmail.com';if(!publicKey||!privateKey)return NextResponse.json({error:'Clés VAPID absentes.'},{status:503});webpush.setVapidDetails(subject,publicKey,privateKey);const reopening=await claimReopening(new Date());let reopeningSent=0,reopeningFailed=0;if(reopening?.general.reopeningPushEnabled){const subscriptions=await listPushSubscriptions();const payload=JSON.stringify({title:reopening.general.reopeningNotificationTitle,body:reopening.general.reopeningNotificationMessage,url:'/'});await Promise.all(subscriptions.map(async row=>{try{await webpush.sendNotification(row.subscription as PushSubscription,payload);reopeningSent++}catch(error){reopeningFailed++;const statusCode=typeof error==='object'&&error&&'statusCode'in error?Number(error.statusCode):0;if(statusCode===404||statusCode===410)await deletePushSubscription(row.endpoint)}}))}const offers=await listOffersNeedingReminder();let sent=0;for(const offer of offers){const subscriptions=await listPushSubscriptions(offer.member_id);let success=false;for(const row of subscriptions){try{await webpush.sendNotification(row.subscription as PushSubscription,JSON.stringify({title:'Votre offre Club LBDC expire bientôt',body:'Plus que 2 jours pour profiter de vos 10 % de remise de bienvenue.',url:'/club/espace'}));sent++;success=true}catch{}}if(success)await markReminderSent(offer.id)}return NextResponse.json({ok:true,offers:offers.length,sent,reopening:Boolean(reopening),reopeningSent,reopeningFailed})}
