import {NextRequest,NextResponse} from 'next/server';import {randomUUID,createHmac} from 'node:crypto';import sharp from 'sharp';import {db,settings,reviewInput} from '@/lib/final-features';
export const runtime='nodejs';export const maxDuration=60;
export async function GET(){try{return NextResponse.json({reviews:await db('site_reviews?status=eq.published&select=id,name,rating,comment,photo_ids,created_at&order=created_at.desc&limit=100')},{headers:{'Cache-Control':'no-store'}})}catch{return NextResponse.json({reviews:[],unavailable:true},{headers:{'Cache-Control':'no-store'}})}}
export async function POST(r:NextRequest){const uploaded:string[]=[];let config:{url:string;key:string}|undefined;try{
 if(r.headers.get('origin')&&r.headers.get('origin')!==r.nextUrl.origin)return NextResponse.json({error:'Origine refusée'},{status:403});
 const announced=Number(r.headers.get('content-length')||0);if(announced>3600000)throw new Error('Envoi trop volumineux.');
 const reader=r.body?.getReader();if(!reader)throw new Error('Formulaire manquant');let size=0;const chunks:Uint8Array[]=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>3600000){await reader.cancel();throw new Error('Envoi trop volumineux.')}chunks.push(value)}
 const f=await new Response(Buffer.concat(chunks),{headers:{'Content-Type':r.headers.get('content-type')||''}}).formData();
 if(f.get('website'))throw new Error('Envoi refusé.');if(f.get('consent')!=='true')throw new Error('Consentement requis.');const input=reviewInput({name:f.get('name'),rating:f.get('rating'),comment:f.get('comment')});const photos=f.getAll('photos');if(photos.length>5)throw new Error('5 photos maximum.');
 config=settings();const fingerprint=createHmac('sha256',config.key).update(r.headers.get('x-vercel-forwarded-for')||r.headers.get('x-real-ip')||'unknown').digest('hex');await db('rpc/reserve_site_review','POST',{p_fingerprint:fingerprint});
 const id=randomUUID(),ids:string[]=[];
 for(const item of photos){if(!(item instanceof File)||!['image/jpeg','image/png','image/webp'].includes(item.type)||item.size>650000||!item.size)throw new Error('Photo non valide (JPEG, PNG ou WebP, 650 Ko maximum après préparation).');const raw=Buffer.from(await item.arrayBuffer()),meta=await sharp(raw,{limitInputPixels:25000000,failOn:'error'}).metadata();if(!['jpeg','png','webp'].includes(meta.format||''))throw new Error('Format photo invalide');const bytes=await sharp(raw,{limitInputPixels:25000000,failOn:'error'}).rotate().resize({width:1600,height:1600,fit:'inside',withoutEnlargement:true}).flatten({background:'#ffffff'}).jpeg({quality:78}).timeout({seconds:8}).toBuffer();if(bytes.length>800000)throw new Error('Photo trop volumineuse');const pid=randomUUID(),object=id+'/'+pid+'.jpg';const upload=await fetch(config.url+'/storage/v1/object/review-photos/'+object,{method:'POST',headers:{apikey:config.key,Authorization:'Bearer '+config.key,'Content-Type':'image/jpeg'},body:new Uint8Array(bytes),signal:AbortSignal.timeout(15000)});if(!upload.ok)throw new Error('Envoi photo impossible. Réessayez.');uploaded.push(object);ids.push(pid)}
 await db('site_reviews','POST',{id,...input,consent:true,status:'pending',photo_ids:ids});return NextResponse.json({ok:true,message:'Merci pour votre avis. Il sera publié après validation par notre équipe.'},{status:201});
 }catch(e){if(config&&uploaded.length)await fetch(config.url+'/storage/v1/object/review-photos',{method:'DELETE',headers:{apikey:config.key,Authorization:'Bearer '+config.key,'Content-Type':'application/json'},body:JSON.stringify({prefixes:uploaded}),signal:AbortSignal.timeout(5000)}).catch(()=>{});return NextResponse.json({error:e instanceof Error?e.message:'Envoi impossible'},{status:400})}}
