'use client'
import {useEffect,useState} from 'react'
type Promotion={id:string;title:string;description:string;start_at:string;end_at:string;discount_label:string;product_label:string;active:boolean}
const localInput=(d:Date)=>{const p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
export function AdminPromotionsPanel({password}:{password:string}){const now=new Date();const tomorrow=new Date(Date.now()+86400000);const[title,setTitle]=useState('Offre réservée aux membres');const[description,setDescription]=useState('Présentez votre QR code de fidélité pour profiter de cette offre.');const[discountLabel,setDiscountLabel]=useState('-20 %');const[productLabel,setProductLabel]=useState('sur le produit de votre choix');const[startAt,setStartAt]=useState(localInput(now));const[endAt,setEndAt]=useState(localInput(tomorrow));const[items,setItems]=useState<Promotion[]>([]);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false)
 async function load(){const r=await fetch('/api/club/promotions',{headers:{'x-admin-password':password},cache:'no-store'});const d=await r.json();if(r.ok)setItems(d.promotions||[]);else setMessage(d.error||'Lecture impossible.')}
 useEffect(()=>{if(password)load()},[password])
 async function create(sendPush:boolean){setBusy(true);setMessage('Création…');const r=await fetch('/api/club/promotions',{method:'POST',headers:{'Content-Type':'application/json','x-admin-password':password},body:JSON.stringify({title,description,discountLabel,productLabel,startAt:new Date(startAt).toISOString(),endAt:new Date(endAt).toISOString()})});const d=await r.json();if(!r.ok){setMessage(d.error||'Création impossible.');setBusy(false);return}if(sendPush){const body=[discountLabel,productLabel,description].filter(Boolean).join(' — ');const push=await fetch('/api/push/send',{method:'POST',headers:{'Content-Type':'application/json','x-admin-password':password},body:JSON.stringify({title:`🎁 ${title}`,body,url:'/club/espace'})});const pd=await push.json();setMessage(push.ok?`Promotion publiée et notification envoyée à ${pd.sent} abonné(s).`:`Promotion publiée, notification non envoyée : ${pd.error||'erreur'}`)}else setMessage('Promotion publiée dans l’espace membre.');await load();setBusy(false)}
 async function toggle(p:Promotion){await fetch('/api/club/promotions',{method:'PATCH',headers:{'Content-Type':'application/json','x-admin-password':password},body:JSON.stringify({id:p.id,active:!p.active})});await load()}
 return <section className="club-admin-section"><div className="club-admin-heading"><div><span className="club-badge">COMMUNICATION</span><h2>Promotions réservées aux membres</h2></div></div><div className="promotion-form-grid"><label>Titre<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Avantage<input value={discountLabel} onChange={e=>setDiscountLabel(e.target.value)} placeholder="-20 %"/></label><label>Produit concerné<input value={productLabel} onChange={e=>setProductLabel(e.target.value)} placeholder="sur les planches"/></label><label>Début<input type="datetime-local" value={startAt} onChange={e=>setStartAt(e.target.value)}/></label><label>Fin<input type="datetime-local" value={endAt} onChange={e=>setEndAt(e.target.value)}/></label><label className="promotion-description">Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label></div><div className="actions"><button className="button secondary" disabled={busy} onClick={()=>create(false)}>Publier sans notification</button><button className="button" disabled={busy} onClick={()=>create(true)}>Publier et notifier</button></div>{message&&<p className="admin-help">{message}</p>}<div className="club-member-list">{items.map(p=><article className="club-member-card" key={p.id}><div><strong>{p.title}</strong><small>{p.discount_label} {p.product_label}</small><small>{new Date(p.start_at).toLocaleString('fr-FR')} → {new Date(p.end_at).toLocaleString('fr-FR')}</small></div><button className="button secondary compact" onClick={()=>toggle(p)}>{p.active?'Désactiver':'Réactiver'}</button></article>)}</div></section>}
