'use client'
import Link from 'next/link'
import { useEffect,useMemo,useState } from 'react'
import { PushSubscriptionManager } from '@/components/push-subscription'
import { useSiteContent } from '@/components/content-provider'

type WelcomeOffer={token:string;createdAt:string;expiresAt:string;usedAt:string|null;discountRate:number;discountAmount:number}
type PromotionCoupon={token:string;promotionId:string;expiresAt:string;usedAt:string|null;discountRate:number;discountAmount:number;title:string;description:string;productLabel:string}
type LoyaltyEvent={id:string;type:'passage'|'reward';date:string;value:number;note:string}
type Member={firstName:string;lastName:string;email:string;birthday:string|null;personalCode:string;loyaltyPoints:number;rewardAvailable:boolean;emailMarketing:boolean;notificationInterest:boolean;createdAt:string;welcomeOffer:WelcomeOffer;promotionCoupons:PromotionCoupon[];loyaltyEvents:LoyaltyEvent[]}
type Promotion={id:string;title:string;description:string;start_at:string;end_at:string;discount_label:string;product_label:string;coupon_enabled?:boolean}
type AvailableItem={id:string;kind:'coupon'|'reward'|'offer';title:string;description:string;value:string;expiresAt:string|null;qr?:string}
type HistoryItem={id:string;date:string;type:string;value:string;amount:number;isDiscount:boolean}

const STORAGE_KEY='club-lbdc-member'
const money=(value:number)=>value.toLocaleString('fr-FR',{style:'currency',currency:'EUR'})
const formatDate=(value:string)=>new Date(value).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'})

export function ClubMemberSpace(){
 const {club}=useSiteContent();const[sessionLoading,setSessionLoading]=useState(true);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[member,setMember]=useState<Member|null>(null);const[promotions,setPromotions]=useState<Promotion[]>([]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('')
 async function loadPromotions(){try{const r=await fetch('/api/club/promotions',{cache:'no-store'});const d=await r.json();if(r.ok)setPromotions(d.promotions||[])}catch{}}
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');if(p.email)setEmail(p.email)}catch{};const restore=async()=>{try{const r=await fetch('/api/club/session',{cache:'no-store'});const d=await r.json();if(r.ok&&d.member){setMember(d.member);setEmail(d.member.email);localStorage.setItem(STORAGE_KEY,JSON.stringify({email:d.member.email}));loadPromotions()}}catch{}finally{setSessionLoading(false)}};restore()},[])
 async function login(){setBusy(true);setMessage('Connexion en cours…');const r=await fetch('/api/club/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(r.ok){setMember(d.member);localStorage.setItem(STORAGE_KEY,JSON.stringify({email:d.member.email}));setMessage('');loadPromotions()}else{setMember(null);setMessage(d.error||'Connexion impossible.')}setBusy(false)}
 useEffect(()=>{if(!member?.welcomeOffer?.token||member.welcomeOffer.usedAt)return;const refresh=async()=>{try{const r=await fetch(`/api/club/welcome-status?token=${encodeURIComponent(member.welcomeOffer.token)}`,{cache:'no-store'});const d=await r.json();if(r.ok&&d.usedAt)setMember(current=>current?{...current,welcomeOffer:{...current.welcomeOffer,usedAt:d.usedAt,expiresAt:d.expiresAt,discountAmount:d.discountAmount}}:current)}catch{}};const timer=window.setInterval(refresh,10000);return()=>window.clearInterval(timer)},[member?.welcomeOffer?.token,member?.welcomeOffer?.usedAt])
 useEffect(()=>{if(!member?.promotionCoupons?.length)return;const refresh=async()=>{const updated=await Promise.all(member.promotionCoupons.map(async c=>{if(c.usedAt)return c;try{const r=await fetch(`/api/club/coupon-status?token=${encodeURIComponent(c.token)}`,{cache:'no-store'});const d=await r.json();return r.ok?{...c,usedAt:d.usedAt,expiresAt:d.expiresAt,discountAmount:d.discountAmount}:c}catch{return c}}));setMember(current=>current?{...current,promotionCoupons:updated}:current)};const timer=window.setInterval(refresh,10000);return()=>window.clearInterval(timer)},[member?.promotionCoupons?.map(c=>`${c.token}:${c.usedAt||''}`).join('|')])
 async function logout(){await fetch('/api/club/session',{method:'DELETE'}).catch(()=>undefined);localStorage.removeItem(STORAGE_KEY);setMember(null);setPassword('');setMessage('Vous êtes déconnecté.')}

 const dashboard=useMemo(()=>{if(!member)return null;const now=Date.now();const activeCoupons=member.promotionCoupons.filter(c=>!c.usedAt&&new Date(c.expiresAt).getTime()>=now);const couponPromotionIds=new Set(member.promotionCoupons.map(c=>c.promotionId));const available:AvailableItem[]=[];if(!member.welcomeOffer.usedAt&&new Date(member.welcomeOffer.expiresAt).getTime()>=now)available.push({id:'welcome',kind:'coupon',title:'Cadeau de bienvenue',description:'10 % de remise sur votre prochaine addition.',value:`-${member.welcomeOffer.discountRate} %`,expiresAt:member.welcomeOffer.expiresAt,qr:`/api/club/welcome-qr?token=${encodeURIComponent(member.welcomeOffer.token)}`});for(const c of activeCoupons)available.push({id:c.token,kind:'coupon',title:c.title,description:c.description,value:`-${c.discountRate} % ${c.productLabel}`,expiresAt:c.expiresAt,qr:`/api/club/coupon-qr?token=${encodeURIComponent(c.token)}`});if(member.rewardAvailable)available.push({id:'reward',kind:'reward',title:club.rewards[0]||'Récompense fidélité',description:'Présentez votre carte de fidélité au Bistrot.',value:'Cadeau',expiresAt:null});for(const p of promotions.filter(p=>!couponPromotionIds.has(p.id)))available.push({id:p.id,kind:'offer',title:p.title,description:p.description,value:`${p.discount_label} ${p.product_label}`,expiresAt:p.end_at});available.sort((a,b)=>(a.expiresAt?new Date(a.expiresAt).getTime():Number.MAX_SAFE_INTEGER)-(b.expiresAt?new Date(b.expiresAt).getTime():Number.MAX_SAFE_INTEGER));const history:HistoryItem[]=[];if(member.welcomeOffer.usedAt)history.push({id:'welcome-used',date:member.welcomeOffer.usedAt,type:'Coupon de bienvenue',value:money(member.welcomeOffer.discountAmount),amount:member.welcomeOffer.discountAmount,isDiscount:true});for(const c of member.promotionCoupons.filter(c=>c.usedAt))history.push({id:`coupon-${c.token}`,date:c.usedAt!,type:`Coupon promotionnel — ${c.title}`,value:money(c.discountAmount),amount:c.discountAmount,isDiscount:true});for(const e of member.loyaltyEvents.filter(e=>e.type==='reward'))history.push({id:e.id,date:e.date,type:'Récompense fidélité',value:e.note||money(e.value),amount:e.value,isDiscount:false});history.sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());const stamps=member.loyaltyEvents.filter(e=>e.type==='passage').length;const rewards=member.loyaltyEvents.filter(e=>e.type==='reward').length;const coupons=history.filter(h=>h.isDiscount).length;const discounts=history.filter(h=>h.isDiscount).reduce((sum,h)=>sum+h.amount,0);const gifts=history.filter(h=>!h.isDiscount).reduce((sum,h)=>sum+h.amount,0);return{available,history,stats:{stamps,rewards,coupons,discounts,gifts,total:discounts+gifts}}},[member,promotions,club.rewards])

 if(sessionLoading)return <section className="member-login-card"><span className="club-badge">Espace membre</span><h2>Ouverture de votre espace…</h2><p>Votre connexion est vérifiée automatiquement.</p></section>
 if(!member)return <section className="member-login-card"><span className="club-badge">Espace membre</span><h2>Accéder à mon espace</h2><p>Connectez-vous avec votre adresse e-mail et votre mot de passe.</p><label>Adresse e-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" onKeyDown={e=>{if(e.key==='Enter')login()}}/></label><button className="button" disabled={busy||!email||!password} onClick={login}>{busy?'Connexion…':'Se connecter'}</button>{message&&<p className="admin-login-message">{message}</p>}<p className="member-help">Pas encore membre ? <Link className="text-link" href="/club">Rejoindre le Club LBDC</Link></p></section>
 if(!dashboard)return null
 return <section className="member-dashboard"><div className="member-dashboard-head"><div><span className="club-badge">Membre du Club</span><h2>Bonjour {member.firstName} {member.lastName} 👋</h2><p>{club.presentation}</p></div><button className="button secondary" onClick={logout}>Se déconnecter</button></div>
  <details className="club-dashboard-section" open><summary><span>{club.availableTitle}</span><b>{dashboard.available.length}</b></summary><div className="club-dashboard-body">{dashboard.available.length===0?<p className="club-empty-state">Vous n’avez aucun avantage disponible pour le moment.</p>:<div className="club-available-list">{dashboard.available.map(item=><article className="club-advantage-card" key={item.id}><div><span className="club-advantage-type">{item.kind==='coupon'?'Coupon':item.kind==='reward'?'Récompense':'Offre'}</span><h3>{item.title}</h3><strong className="promotion-value">{item.value}</strong><p>{item.description}</p>{item.expiresAt?<small>Valable jusqu’au {new Date(item.expiresAt).toLocaleString('fr-FR')}</small>:<small>Disponible dès aujourd’hui</small>}</div>{item.qr&&<img src={item.qr} alt={`QR code ${item.title}`}/>}</article>)}</div>}</div></details>
  <details className="club-dashboard-section"><summary><span>{club.historyTitle}</span><b>{dashboard.history.length}</b></summary><div className="club-dashboard-body">{dashboard.history.length===0?<p className="club-empty-state">Aucun avantage utilisé pour le moment.</p>:<div className="club-history-wrap"><table className="club-history-table"><thead><tr><th>Date</th><th>Type d’avantage</th><th>Remise ou cadeau</th><th>Statut</th></tr></thead><tbody>{dashboard.history.map(item=><tr key={item.id}><td>{formatDate(item.date)}</td><td>{item.type}</td><td>{item.value}</td><td><span className="club-used-status">Utilisé</span></td></tr>)}</tbody></table></div>}</div></details>
  <details className="club-dashboard-section" open><summary><span>{club.summaryTitle}</span></summary><div className="club-dashboard-body"><p className="club-savings-message">{club.savingsMessage.replace('{amount}',money(dashboard.stats.total))}</p><div className="club-summary-grid"><article><strong>{dashboard.stats.stamps}</strong><span>Tampons gagnés</span></article><article><strong>{dashboard.stats.rewards}</strong><span>Récompenses obtenues</span></article><article><strong>{dashboard.stats.coupons}</strong><span>Coupons utilisés</span></article><article><strong>{money(dashboard.stats.total)}</strong><span>Total économisé</span></article><article><strong>{money(dashboard.stats.discounts)}</strong><span>Total des remises</span></article><article><strong>{dashboard.stats.rewards}</strong><span>Cadeaux reçus</span></article></div></div></details>
  <section className="club-program-copy"><h3>Comment fonctionne le Club ?</h3><p>{club.programExplanation}</p><ul>{club.rewards.map((reward,index)=><li key={index}>{reward}</li>)}</ul><small>{club.conditions}</small></section>
  <div className="member-code-card qr-member-card"><h3>Ma carte de fidélité</h3><img src={`/api/club/qr?code=${encodeURIComponent(member.personalCode)}`} alt="QR code personnel de fidélité"/><p>Présentez ce QR code au Bistrot pour ajouter un repas à votre fidélité.</p><strong>{member.loyaltyPoints}/10 tampons sur votre carte actuelle</strong></div><PushSubscriptionManager memberCode={member.personalCode}/><div className="actions"><Link className="button" href="/aujourdhui">Menu du jour</Link><Link className="button secondary" href="/evenements">Événements</Link><Link className="button secondary" href="/application">Installer l’application</Link></div>
 </section>
}
