'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
type Member={firstName:string;lastName:string;email:string;birthday:string|null;personalCode:string;loyaltyPoints:number;rewardAvailable:boolean;emailMarketing:boolean;notificationInterest:boolean;createdAt:string}
const STORAGE_KEY='club-lbdc-member'
export function ClubMemberSpace(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [member,setMember]=useState<Member|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');useEffect(()=>{try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');if(p.email)setEmail(p.email)}catch{}},[])
 async function login(){setBusy(true);setMessage('Connexion en cours…');const r=await fetch('/api/club/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(r.ok){setMember(d.member);localStorage.setItem(STORAGE_KEY,JSON.stringify({email:d.member.email}));setMessage('')}else{setMember(null);setMessage(d.error||'Connexion impossible.')}setBusy(false)}
 function logout(){localStorage.removeItem(STORAGE_KEY);setMember(null);setPassword('');setMessage('Vous êtes déconnecté.')}
 if(!member)return <section className="member-login-card"><span className="club-badge">Espace membre</span><h2>Accéder à mon espace</h2><p>Connectez-vous avec votre adresse e-mail et votre mot de passe.</p><label>Adresse e-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" onKeyDown={e=>{if(e.key==='Enter')login()}}/></label><button className="button" disabled={busy||!email||!password} onClick={login}>{busy?'Connexion…':'Se connecter'}</button>{message&&<p className="admin-login-message">{message}</p>}<p className="member-help">Pas encore membre ? <Link className="text-link" href="/club">Rejoindre le Club LBDC</Link></p></section>
 return <section className="member-dashboard"><div className="member-dashboard-head"><div><span className="club-badge">Membre du Club</span><h2>Bonjour {member.firstName} {member.lastName} 👋</h2><p>{member.email}</p></div><button className="button secondary" onClick={logout}>Se déconnecter</button></div><div className="member-cards"><article><span>⭐</span><strong>{member.loyaltyPoints}/10</strong><p>Repas enregistrés</p></article><article><span>🎁</span><strong>{member.rewardAvailable?'Disponible':'À venir'}</strong><p>Formule offerte</p></article><article><span>🔔</span><strong>{member.notificationInterest?'Activées':'Non demandées'}</strong><p>Notifications souhaitées</p></article></div><div className="member-code-card qr-member-card"><h3>Ma carte de fidélité</h3><img src={`/api/club/qr?code=${encodeURIComponent(member.personalCode)}`} alt="QR code personnel de fidélité"/><p>Présentez ce QR code au Bistrot. Il sera scanné pour ajouter un repas à votre fidélité.</p></div><div className="actions"><Link className="button" href="/aujourdhui">Menu du jour</Link><Link className="button secondary" href="/evenements">Événements</Link><Link className="button secondary" href="/application">Installer l’application</Link></div></section>}
