'use client'
import { useState } from 'react'
import Link from 'next/link'

export function ClubSignup(){
 const [firstName,setFirstName]=useState('');const [lastName,setLastName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [birthday,setBirthday]=useState('');const [emailMarketing,setEmailMarketing]=useState(false);const [notificationInterest,setNotificationInterest]=useState(true);const [privacyAccepted,setPrivacyAccepted]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [success,setSuccess]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('Inscription en cours…');const r=await fetch('/api/club/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName,lastName,email,password,birthday,emailMarketing,notificationInterest,privacyAccepted})});const d=await r.json();if(r.ok){setSuccess(true);setMessage(`Bienvenue au Club LBDC, ${d.member.firstName} !`);localStorage.setItem('club-lbdc-member',JSON.stringify({email}));}else setMessage(d.error||'Inscription impossible.');setBusy(false)}
 if(success)return <div className="club-success"><span className="club-badge">CLUB LBDC</span><h2>{message}</h2><p>Votre compte est créé. Vous pourrez désormais vous connecter avec votre adresse e-mail et votre mot de passe.</p><div className="actions"><Link className="button" href="/club/espace">Ouvrir mon espace</Link><Link className="button secondary" href="/application">Installer l’application</Link></div></div>
 return <form className="club-form" onSubmit={submit}><span className="club-badge">Inscription gratuite</span><h2>Rejoindre le Club LBDC</h2><p>Recevez les menus, les événements et les avantages réservés aux membres.</p><div className="club-form-grid"><label>Prénom<input required minLength={2} value={firstName} onChange={e=>setFirstName(e.target.value)} autoComplete="given-name"/></label><label>Nom de famille<input required minLength={2} value={lastName} onChange={e=>setLastName(e.target.value)} autoComplete="family-name"/></label><label>Adresse e-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Mot de passe <small>(8 caractères minimum)</small><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><label>Date d’anniversaire <small>(facultative)</small><input type="date" value={birthday} onChange={e=>setBirthday(e.target.value)}/></label></div><label className="checkbox-label club-check"><input type="checkbox" checked={notificationInterest} onChange={e=>setNotificationInterest(e.target.checked)}/> Je souhaite recevoir les notifications du menu et des événements.</label><label className="checkbox-label club-check"><input type="checkbox" checked={emailMarketing} onChange={e=>setEmailMarketing(e.target.checked)}/> J’accepte de recevoir occasionnellement des offres du Bistrot par e-mail.</label><label className="checkbox-label club-check"><input required type="checkbox" checked={privacyAccepted} onChange={e=>setPrivacyAccepted(e.target.checked)}/> J’accepte l’enregistrement de ces informations pour gérer mon inscription au Club. Je pourrai demander leur suppression à tout moment.</label><button className="button club-submit" disabled={busy}>{busy?'Veuillez patienter…':'Rejoindre le Club'}</button>{message&&<p className="admin-login-message" aria-live="polite">{message}</p>}</form>
}
