'use client';
import {useEffect,useState} from 'react';import {useLanguage} from './language-provider';import styles from './member-extras.module.css';
type Option={id:string;category:string;label:string;active:boolean;translations?:Record<string,string>};
const categories=[['entrees','Mes entrées préférées','Choisissez jusqu’à 4 entrées parmi les propositions suivantes'],['plats','Mes plats préférés','Choisissez jusqu’à 4 plats parmi les propositions suivantes'],['desserts','Mes desserts préférés','Choisissez jusqu’à 4 desserts parmi les propositions suivantes']];
export default function MemberPreferences(){const {t,locale}=useLanguage();const [options,setOptions]=useState<Option[]>([]),[selected,setSelected]=useState<string[]>([]),[enabled,setEnabled]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let live=true;fetch('/api/club/preferences',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{if(live){setOptions(d.options);setSelected(d.preferences.items.map((i:{option_id:string})=>i.option_id));setEnabled(d.preferences.notifications_enabled);setLoaded(true)}}).catch(()=>{if(live)setMessage('Préférences momentanément indisponibles.')});return()=>{live=false}},[]);
 function toggle(o:Option){setMessage('');if(selected.includes(o.id)){setSelected(selected.filter(id=>id!==o.id));return}if(!o.active)return;if(options.filter(v=>v.category===o.category&&selected.includes(v.id)).length>=4){setMessage('Vous pouvez sélectionner jusqu’à 4 favoris dans cette catégorie.');return}setSelected([...selected,o.id])}
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/club/preferences',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:selected.map(option_id=>({option_id})),notifications_enabled:enabled})});if(!r.ok)throw Error();setMessage('Préférences enregistrées.')}catch{setMessage('Enregistrement impossible. Réessayez dans un instant.')}finally{setBusy(false)}}
 return <details className="club-dashboard-section"><summary><span>{t('Mon profil · Mes préférences')}</span></summary><div className="club-dashboard-body"><p>{t('Ces choix sont facultatifs et privés. Ils nous aident à vous proposer des menus et des offres qui vous plaisent.')}</p>{loaded&&<>{categories.map(([key,title,instruction])=><section className={styles.preferenceGroup} key={key}><h3>{t(title)}</h3><p>{t(instruction)}</p><small>{t('{count} / 4 sélectionnés',{count:options.filter(o=>o.category===key&&selected.includes(o.id)).length})}</small><div className={styles.pills}>{options.filter(o=>o.category===key&&(o.active||selected.includes(o.id))).map(o=><button className={styles.pill} key={o.id} type="button" aria-pressed={selected.includes(o.id)} onClick={()=>toggle(o)}>{selected.includes(o.id)&&<span aria-hidden="true">✓ </span>}{(locale!=='fr'&&o.translations?.[locale])||o.label}{!o.active&&' · '+t('Archivé')}</button>)}</div>{!options.some(o=>o.category===key&&o.active)&&<p>{t('De nouvelles propositions seront bientôt disponibles.')}</p>}</section>)}<label className="checkbox-label club-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>{t('Me prévenir quand un de mes favoris est au Menu du jour.')}</label><p><small>{t('Activez aussi les notifications sur cet appareil. Une seule alerte sera envoyée par publication, même si plusieurs favoris correspondent.')}</small></p><button type="button" className="button" disabled={busy} onClick={save}>{t(busy?'Enregistrement…':'Enregistrer mes préférences')}</button></>}<p role="status">{t(message)}</p></div></details>
}
