'use client';
import {useEffect,useState} from 'react';import {preparePhoto} from '@/lib/photo-client';import styles from './member-extras.module.css';
type Data={code:string;enabled:boolean;rules:{id:string;audience:string;threshold:number;label:string;benefit:string}[];referrals:{id:string;created_at:string;validated_at:string|null}[];rewards:{id:string;label:string;benefit:string;created_at:string;used_at:string|null}[]};
export default function MemberExtras({firstName,lastName}:{firstName:string;lastName:string}){const [avatar,setAvatar]=useState<string|null>(null),[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[photoMessage,setPhotoMessage]=useState(''),[message,setMessage]=useState(''),[link,setLink]=useState('');
 useEffect(()=>{let live=true;fetch('/api/club/profile',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(live)setAvatar(d.avatar||null)}).catch(()=>{});fetch('/api/club/referrals',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{if(live){setData(d);setLink(window.location.origin+'/club?ref='+encodeURIComponent(d.code))}}).catch(()=>{if(live)setMessage('Parrainage momentanément indisponible.')});return()=>{live=false}},[]);
 async function photo(file?:File){setBusy(true);setPhotoMessage('');try{let body:FormData|undefined;if(file){body=new FormData();body.set('photo',await preparePhoto(file))}const r=await fetch('/api/club/profile',{method:file?'POST':'DELETE',body}),d=await r.json();if(!r.ok)throw Error();setAvatar(d.avatar);setPhotoMessage(file?'Photo enregistrée.':'Photo supprimée.')}catch{setPhotoMessage('Photo non enregistrée. Choisissez un JPEG, PNG ou HEIC/HEIF lisible et réessayez.')}finally{setBusy(false)}}
 const count=data?.referrals.filter(r=>r.validated_at).length||0,next=data?.rules.find(r=>r.audience==='sponsor'&&r.threshold>count);const invitation='Rejoins le Club LBDC du Bistrot Du Coin avec mon code : '+(data?.code||'')+'. Profite des avantages et offres du Club. '+link;
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setMessage('Copié.')}catch{setMessage('Sélectionnez puis copiez le code ou le lien ci-dessous.')}}
 async function share(){try{if(navigator.share)await navigator.share({title:'Club LBDC',text:'Rejoins le Club LBDC avec mon code : '+data?.code,url:link});else await copy(invitation)}catch(e){if(!(e instanceof Error&&e.name==='AbortError'))setMessage('Partage indisponible. Copiez le lien ci-dessous.')}}
 return <div className={styles.extras}><div className={styles.profile}>{avatar?<img src={avatar} alt={'Photo de '+firstName} width={64} height={64} onError={()=>setAvatar(null)}/>:<span className={styles.initials} aria-label="Avatar avec initiales">{firstName.slice(0,1)}{lastName.slice(0,1)}</span>}<div><strong>{firstName}</strong><details><summary>Ma photo de profil</summary><p>Cadrage carré centré, affichage rond. Photo privée.</p><input aria-label="Photo de profil" type="file" accept=".jpg,.jpeg,.png,.webp,.heic,.heif" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void photo(file)}}/>{avatar&&<button type="button" disabled={busy} onClick={()=>photo()}>Supprimer ma photo</button>}</details><p role="status">{busy?'Préparation de la photo…':photoMessage}</p></div></div><details className="club-dashboard-section"><summary><span>Parrainage</span><b>{count} ami{count>1?'s':''}</b></summary><div className="club-dashboard-body">{data&&<><h3>Inviter un proche</h3><p>{data.enabled?(next?'Prochaine récompense à '+next.threshold+' parrainages validés : '+next.label:'Vos récompenses de parrainage'):'Les nouvelles invitations sont momentanément désactivées.'}</p><label>Mon code<input readOnly value={data.code}/></label><div className="actions"><button type="button" onClick={()=>copy(data.code)}>Copier mon code</button><button type="button" onClick={share}>Partager mon code</button></div><input aria-label="Lien de parrainage" readOnly value={link}/><div className="actions"><a href={'sms:?body='+encodeURIComponent(invitation)}>SMS</a><a href={'https://wa.me/?text='+encodeURIComponent(invitation)} target="_blank" rel="noreferrer">WhatsApp</a><a href={'mailto:?subject=Invitation%20Club%20LBDC&body='+encodeURIComponent(invitation)}>E-mail</a></div><small>Messenger est disponible dans le menu de partage du téléphone s’il est installé ; vous pouvez aussi y coller le lien.</small><p>{data.referrals.filter(r=>!r.validated_at).length} invitation(s) en attente de validation.</p>{data.rewards.map(r=><article key={r.id}><strong>{r.label}</strong><p>{r.benefit}</p><small>{r.used_at?'Utilisée le '+new Date(r.used_at).toLocaleDateString('fr-FR'):'Disponible — à présenter à l’équipe'} · {r.id.slice(0,8)}</small></article>)}{!data.rewards.length&&<p>Aucune récompense obtenue pour le moment.</p>}</>}<p role="status">{message}</p></div></details></div>
}
