import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto'
import { getFullFormulaPrice } from '@/lib/site-pricing'
import { ensureWelcomeOffer } from '@/lib/welcome-offer-store'

export type ClubMember = {
  id: string; first_name: string; last_name: string; email: string; birthday: string | null;
  email_marketing: boolean; notification_interest: boolean; loyalty_points: number;
  reward_available: boolean; personal_code: string; created_at: string
}
export type LoyaltyEvent = {
  id:string; member_id:string; event_type:'passage'|'reward'; event_day:string; created_at:string;
  receipt_number:string|null; reward_value_ttc:number|null; note:string|null;
  club_members?: Pick<ClubMember,'first_name'|'last_name'|'email'|'personal_code'>
}
const settings=()=>({url:process.env.SUPABASE_URL?.replace(/\/$/,''),key:process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY})
const headers=()=>{const {key}=settings();return {apikey:key||'',Authorization:`Bearer ${key||''}`,'Content-Type':'application/json'}}
export function clubStorageConfigured(){const {url,key}=settings();return Boolean(url&&key)}
const memberSelect='id,first_name,last_name,email,birthday,email_marketing,notification_interest,loyalty_points,reward_available,personal_code,created_at'
function hashPassword(password:string,salt=randomBytes(16).toString('hex')){return {salt,hash:scryptSync(password,salt,64).toString('hex')}}
function verifyPassword(password:string,salt:string,expected:string){const actual=scryptSync(password,salt,64);const target=Buffer.from(expected,'hex');return actual.length===target.length&&timingSafeEqual(actual,target)}
function requireSettings(){const {url,key}=settings();if(!url||!key)throw new Error('Le Club LBDC n’est pas encore configuré.');return {url,key}}
async function parseError(response:Response,fallback:string){let details='';try{const body=await response.json() as {message?:string;details?:string;code?:string};details=body.message||body.details||body.code||''}catch{}return new Error(details?`${fallback} ${details}`:fallback)}

export async function joinClub(input:{firstName:string;lastName:string;email:string;password:string;birthday?:string;emailMarketing:boolean;notificationInterest:boolean}){
 const {url}=requireSettings();const email=input.email.trim().toLowerCase();const secured=hashPassword(input.password)
 const response=await fetch(`${url}/rest/v1/club_members?on_conflict=email`,{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({first_name:input.firstName.trim(),last_name:input.lastName.trim(),email,birthday:input.birthday||null,email_marketing:input.emailMarketing,notification_interest:input.notificationInterest,password_hash:secured.hash,password_salt:secured.salt,consent_updated_at:new Date().toISOString()}),cache:'no-store'})
 if(!response.ok)throw await parseError(response,`Inscription impossible (${response.status}).`);const rows=await response.json() as ClubMember[];const member=rows[0];await ensureWelcomeOffer(member.id);return member
}
export async function listClubMembers():Promise<ClubMember[]>{const {url}=requireSettings();const r=await fetch(`${url}/rest/v1/club_members?select=${memberSelect}&order=created_at.desc`,{headers:headers(),cache:'no-store'});if(!r.ok)throw await parseError(r,`Lecture impossible (${r.status}).`);return r.json()}
export async function getClubMemberByPassword(emailInput:string,password:string):Promise<ClubMember|null>{const {url}=requireSettings();const email=emailInput.trim().toLowerCase();const q=new URLSearchParams({select:`${memberSelect},password_hash,password_salt`,email:`eq.${email}`,limit:'1'});const r=await fetch(`${url}/rest/v1/club_members?${q}`,{headers:headers(),cache:'no-store'});if(!r.ok)throw await parseError(r,`Connexion impossible (${r.status}).`);const rows=await r.json() as (ClubMember&{password_hash:string|null;password_salt:string|null})[];const row=rows[0];if(!row?.password_hash||!row.password_salt||!verifyPassword(password,row.password_salt,row.password_hash))return null;const {password_hash,password_salt,...member}=row;return member}
export async function getClubMemberByCode(code:string):Promise<ClubMember|null>{const {url}=requireSettings();const q=new URLSearchParams({select:memberSelect,personal_code:`eq.${code}`,limit:'1'});const r=await fetch(`${url}/rest/v1/club_members?${q}`,{headers:headers(),cache:'no-store'});if(!r.ok)throw await parseError(r,`Lecture impossible (${r.status}).`);const rows=await r.json() as ClubMember[];return rows[0]||null}
async function patchMember(code:string,body:Record<string,unknown>){const {url}=requireSettings();const r=await fetch(`${url}/rest/v1/club_members?personal_code=eq.${encodeURIComponent(code)}`,{method:'PATCH',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify({...body,updated_at:new Date().toISOString()}),cache:'no-store'});if(!r.ok)throw await parseError(r,`Mise à jour impossible (${r.status}).`);const rows=await r.json() as ClubMember[];return rows[0]}
async function insertEvent(event:Record<string,unknown>){const {url}=requireSettings();const r=await fetch(`${url}/rest/v1/club_loyalty_events`,{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(event),cache:'no-store'});if(!r.ok)throw await parseError(r,r.status===409?'Un passage a déjà été enregistré aujourd’hui pour cette personne.':`Historique impossible (${r.status}).`);const rows=await r.json() as LoyaltyEvent[];return rows[0]}
export async function addLoyaltyPoint(code:string){const member=await getClubMemberByCode(code);if(!member)throw new Error('Membre introuvable.');await insertEvent({member_id:member.id,event_type:'passage',event_day:new Date().toISOString().slice(0,10)});const points=Math.min(10,(member.loyalty_points||0)+1);return patchMember(code,{loyalty_points:points,reward_available:points>=10})}
export async function redeemReward(code:string){const member=await getClubMemberByCode(code);if(!member?.reward_available)throw new Error('Aucune récompense disponible.');const formula=await getFullFormulaPrice();const receipt=`LBDC-${new Date().toISOString().replace(/\D/g,'').slice(0,14)}-${member.personal_code.slice(0,6).toUpperCase()}`;const event=await insertEvent({member_id:member.id,event_type:'reward',event_day:new Date().toISOString().slice(0,10),receipt_number:receipt,reward_value_ttc:formula.valueTtc,note:`${formula.name} offerte`});const updated=await patchMember(code,{loyalty_points:0,reward_available:false});return {member:updated,event,formula}}
export async function listLoyaltyEvents():Promise<LoyaltyEvent[]>{const {url}=requireSettings();const select='id,member_id,event_type,event_day,created_at,receipt_number,reward_value_ttc,note,club_members(first_name,last_name,email,personal_code)';const r=await fetch(`${url}/rest/v1/club_loyalty_events?select=${encodeURIComponent(select)}&order=created_at.desc&limit=2000`,{headers:headers(),cache:'no-store'});if(!r.ok)throw await parseError(r,`Lecture de l’historique impossible (${r.status}).`);return r.json()}
export async function listMemberLoyaltyEvents(memberId:string):Promise<LoyaltyEvent[]>{const {url}=requireSettings();const select='id,member_id,event_type,event_day,created_at,receipt_number,reward_value_ttc,note';const q=new URLSearchParams({select,member_id:`eq.${memberId}`,order:'created_at.desc',limit:'2000'});const r=await fetch(`${url}/rest/v1/club_loyalty_events?${q}`,{headers:headers(),cache:'no-store'});if(!r.ok)throw await parseError(r,`Lecture de l’historique impossible (${r.status}).`);return r.json()}
export async function getLoyaltyEventByReceipt(receipt:string):Promise<LoyaltyEvent|null>{const {url}=requireSettings();const select='id,member_id,event_type,event_day,created_at,receipt_number,reward_value_ttc,note,club_members(first_name,last_name,email,personal_code)';const q=new URLSearchParams({select,receipt_number:`eq.${receipt}`,limit:'1'});const r=await fetch(`${url}/rest/v1/club_loyalty_events?${q}`,{headers:headers(),cache:'no-store'});if(!r.ok)throw await parseError(r,`Justificatif introuvable (${r.status}).`);const rows=await r.json() as LoyaltyEvent[];return rows[0]||null}
