import { listClubMembers, listLoyaltyEvents, type ClubMember } from '@/lib/club-store'

export type AudienceType='all'|'new'|'inactive'|'birthdays'|'best'
export type CampaignStatus='draft'|'scheduled'|'sent'|'failed'
export type CommunicationCampaign={id:string;title:string;message:string;url:string;audience_type:AudienceType;audience_days:number|null;scheduled_at:string|null;sent_at:string|null;status:CampaignStatus;recipient_count:number;sent_count:number;failed_count:number;created_at:string}
export type CommunicationTemplate={id:string;name:string;title:string;message:string;url:string;created_at:string}
const settings=()=>({url:process.env.SUPABASE_URL?.replace(/\/$/,''),key:process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY})
const headers=()=>{const {key}=settings();return {apikey:key||'',Authorization:`Bearer ${key||''}`,'Content-Type':'application/json'}}
const requireSettings=()=>{const {url,key}=settings();if(!url||!key)throw new Error('Supabase non configuré.');return {url,key}}
async function parseError(r:Response,label:string){let extra='';try{const d=await r.json() as {message?:string;details?:string};extra=d.message||d.details||''}catch{}return new Error(extra?`${label} ${extra}`:label)}
export async function listCampaigns(){const {url}=requireSettings();const r=await fetch(`${url}/rest/v1/club_communication_campaigns?select=*&order=created_at.desc&limit=200`,{headers:headers(),cache:'no-store'});if(!r.ok)throw await parseError(r,'Lecture des campagnes impossible.');return r.json() as Promise<CommunicationCampaign[]>}
export async function createCampaign(input:{title:string;message:string;url:string;audienceType:AudienceType;audienceDays?:number;scheduledAt?:string|null;status:CampaignStatus}){const {url}=requireSettings();const r=await fetch(`${url}/rest/v1/club_communication_campaigns`,{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify({title:input.title.trim(),message:input.message.trim(),url:input.url||'/club/espace',audience_type:input.audienceType,audience_days:input.audienceDays||null,scheduled_at:input.scheduledAt||null,status:input.status}),cache:'no-store'});if(!r.ok)throw await parseError(r,'Création de campagne impossible.');const rows=await r.json() as CommunicationCampaign[];return rows[0]}
export async function updateCampaign(id:string,body:Partial<CommunicationCampaign>){const {url}=requireSettings();const r=await fetch(`${url}/rest/v1/club_communication_campaigns?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(body),cache:'no-store'});if(!r.ok)throw await parseError(r,'Mise à jour de campagne impossible.');const rows=await r.json() as CommunicationCampaign[];return rows[0]}
export async function listTemplates(){const {url}=requireSettings();const r=await fetch(`${url}/rest/v1/club_communication_templates?select=*&order=created_at.desc`,{headers:headers(),cache:'no-store'});if(!r.ok)throw await parseError(r,'Lecture des modèles impossible.');return r.json() as Promise<CommunicationTemplate[]>}
export async function saveTemplate(input:{name:string;title:string;message:string;url:string}){const {url}=requireSettings();const r=await fetch(`${url}/rest/v1/club_communication_templates`,{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify({name:input.name.trim(),title:input.title.trim(),message:input.message.trim(),url:input.url||'/club/espace'}),cache:'no-store'});if(!r.ok)throw await parseError(r,'Enregistrement du modèle impossible.');const rows=await r.json() as CommunicationTemplate[];return rows[0]}
export async function deleteTemplate(id:string){const {url}=requireSettings();const r=await fetch(`${url}/rest/v1/club_communication_templates?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:headers(),cache:'no-store'});if(!r.ok)throw await parseError(r,'Suppression du modèle impossible.')}
export async function dueCampaigns(){const {url}=requireSettings();const now=new Date().toISOString();const r=await fetch(`${url}/rest/v1/club_communication_campaigns?select=*&status=eq.scheduled&scheduled_at=lte.${encodeURIComponent(now)}&order=scheduled_at.asc`,{headers:headers(),cache:'no-store'});if(!r.ok)throw await parseError(r,'Lecture des campagnes programmées impossible.');return r.json() as Promise<CommunicationCampaign[]>}
export async function resolveAudience(type:AudienceType,days=30):Promise<ClubMember[]>{const members=await listClubMembers();if(type==='all')return members;if(type==='new'){const limit=Date.now()-Math.max(1,days)*86400000;return members.filter(m=>new Date(m.created_at).getTime()>=limit)}if(type==='birthdays'){const now=new Date();const horizon=new Date(Date.now()+Math.max(1,days)*86400000);const dayOfYear=(d:Date)=>Date.UTC(2000,d.getMonth(),d.getDate());return members.filter(m=>{if(!m.birthday)return false;const [,mm,dd]=m.birthday.split('-').map(Number);let target=Date.UTC(now.getFullYear(),mm-1,dd);if(target<Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))target=Date.UTC(now.getFullYear()+1,mm-1,dd);return target<=Date.UTC(horizon.getFullYear(),horizon.getMonth(),horizon.getDate())})}const events=await listLoyaltyEvents();const last=new Map<string,number>();const passages=new Map<string,number>();for(const e of events){if(e.event_type!=='passage')continue;last.set(e.member_id,Math.max(last.get(e.member_id)||0,new Date(e.created_at).getTime()));passages.set(e.member_id,(passages.get(e.member_id)||0)+1)}if(type==='inactive'){const limit=Date.now()-Math.max(1,days)*86400000;return members.filter(m=>(last.get(m.id)||new Date(m.created_at).getTime())<limit)}return [...members].sort((a,b)=>(passages.get(b.id)||0)-(passages.get(a.id)||0)).slice(0,Math.max(1,days))}
