import { decodePromotionProduct, encodePromotionProduct } from '@/lib/product-pricing'
export type ClubPromotion={id:string;title:string;description:string;start_at:string;end_at:string;discount_label:string;product_label:string;active:boolean;created_at:string;coupon_enabled:boolean;discount_rate:number|null;reference_price_ttc:number|null;price_customized:boolean}
type RawPromotion=Omit<ClubPromotion,'reference_price_ttc'|'price_customized'>
type PromotionInput={title:string;description:string;startAt:string;endAt:string;discountLabel:string;productLabel:string;couponEnabled:boolean;discountRate:number|null;referencePrice:number|null;customPrice:boolean}
const settings=()=>({url:process.env.SUPABASE_URL?.replace(/\/$/,''),key:process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY})
const headers=()=>{const{key}=settings();return{apikey:key||'',Authorization:`Bearer ${key||''}`,'Content-Type':'application/json'}}
function configured(){const{url,key}=settings();return Boolean(url&&key)}
const normalizePromotion=(promotion:RawPromotion):ClubPromotion=>{const product=decodePromotionProduct(promotion.product_label);return{...promotion,product_label:product.label,reference_price_ttc:product.referencePrice,price_customized:product.customPrice}}
const promotionBody=(input:PromotionInput)=>({title:input.title.trim(),description:input.description.trim(),start_at:input.startAt,end_at:input.endAt,discount_label:input.discountLabel.trim(),product_label:encodePromotionProduct({label:input.productLabel,referencePrice:input.referencePrice,customPrice:input.customPrice}),coupon_enabled:input.couponEnabled,discount_rate:input.couponEnabled?input.discountRate:null})
export async function listPromotions(activeOnly=false):Promise<ClubPromotion[]>{const{url}=settings();if(!configured()||!url)throw new Error('Supabase non configuré.');const now=new Date().toISOString();const filter=activeOnly?`&active=eq.true&start_at=lte.${encodeURIComponent(now)}&end_at=gte.${encodeURIComponent(now)}`:'';const r=await fetch(`${url}/rest/v1/club_promotions?select=*&order=created_at.desc${filter}`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error(`Lecture des promotions impossible (${r.status}).`);return((await r.json())as RawPromotion[]).map(normalizePromotion)}
export async function createPromotion(input:PromotionInput){const{url}=settings();if(!configured()||!url)throw new Error('Supabase non configuré.');const r=await fetch(`${url}/rest/v1/club_promotions`,{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify({...promotionBody(input),active:true}),cache:'no-store'});if(!r.ok)throw new Error(`Création impossible (${r.status}).`);return normalizePromotion(((await r.json())as RawPromotion[])[0])}
export async function updatePromotion(id:string,input:PromotionInput){const{url}=settings();if(!configured()||!url)throw new Error('Supabase non configuré.');const r=await fetch(`${url}/rest/v1/club_promotions?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(promotionBody(input)),cache:'no-store'});if(!r.ok)throw new Error(`Mise à jour impossible (${r.status}).`);return normalizePromotion(((await r.json())as RawPromotion[])[0])}
export async function setPromotionActive(id:string,active:boolean){const{url}=settings();if(!configured()||!url)throw new Error('Supabase non configuré.');const r=await fetch(`${url}/rest/v1/club_promotions?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...headers(),Prefer:'return=minimal'},body:JSON.stringify({active}),cache:'no-store'});if(!r.ok)throw new Error(`Mise à jour impossible (${r.status}).`)}
