import {decodePromotionProduct} from '@/lib/product-pricing'
export type ClubPromotion={id:string;title:string;description:string;start_at:string;end_at:string;discount_label:string;product_label:string;active:boolean;created_at:string;coupon_enabled:boolean;discount_rate:number|null}
const settings=()=>({url:process.env.SUPABASE_URL?.replace(/\/$/,''),key:process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY})
const headers=()=>{const {key}=settings();return {apikey:key||'',Authorization:`Bearer ${key||''}`,'Content-Type':'application/json'}}
function configured(){const {url,key}=settings();return Boolean(url&&key)}
export async function listPromotions(activeOnly=false):Promise<ClubPromotion[]>{const {url}=settings();if(!configured()||!url)throw new Error('Supabase non configuré.');const now=new Date().toISOString();const filter=activeOnly?`&active=eq.true&start_at=lte.${encodeURIComponent(now)}&end_at=gte.${encodeURIComponent(now)}`:'';const r=await fetch(`${url}/rest/v1/club_promotions?select=*&order=created_at.desc${filter}`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error(`Lecture des promotions impossible (${r.status}).`);const rows=await r.json()as ClubPromotion[];return rows.map(row=>({...row,product_label:decodePromotionProduct(row.product_label).label}))}
export async function createPromotion(input:{title:string;description:string;startAt:string;endAt:string;discountLabel:string;productLabel:string;couponEnabled:boolean;discountRate:number|null}){const {url}=settings();if(!configured()||!url)throw new Error('Supabase non configuré.');const r=await fetch(`${url}/rest/v1/club_promotions`,{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify({title:input.title.trim(),description:input.description.trim(),start_at:input.startAt,end_at:input.endAt,discount_label:input.discountLabel.trim(),product_label:input.productLabel.trim(),active:true,coupon_enabled:input.couponEnabled,discount_rate:input.couponEnabled?input.discountRate:null}),cache:'no-store'});if(!r.ok)throw new Error(`Création impossible (${r.status}).`);const rows=await r.json() as ClubPromotion[];return rows[0]}
export async function updatePromotion(id:string,input:{title:string;description:string;startAt:string;endAt:string;discountLabel:string;productLabel:string;couponEnabled:boolean;discountRate:number|null}){const {url}=settings();if(!configured()||!url)throw new Error('Supabase non configuré.');const r=await fetch(`${url}/rest/v1/club_promotions?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify({title:input.title.trim(),description:input.description.trim(),start_at:input.startAt,end_at:input.endAt,discount_label:input.discountLabel.trim(),product_label:input.productLabel.trim(),coupon_enabled:input.couponEnabled,discount_rate:input.couponEnabled?input.discountRate:null}),cache:'no-store'});if(!r.ok)throw new Error(`Mise à jour impossible (${r.status}).`);const rows=await r.json() as ClubPromotion[];return rows[0]}
export async function setPromotionActive(id:string,active:boolean){const {url}=settings();if(!configured()||!url)throw new Error('Supabase non configuré.');const r=await fetch(`${url}/rest/v1/club_promotions?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...headers(),Prefer:'return=minimal'},body:JSON.stringify({active}),cache:'no-store'});if(!r.ok)throw new Error(`Mise à jour impossible (${r.status}).`)}
