import {NextRequest,NextResponse} from 'next/server'
import webpush,{type PushSubscription} from 'web-push'
import {createCampaign,deleteTemplate,listCampaigns,listTemplates,resolveAudience,saveTemplate,updateCampaign,type AudienceType} from '@/lib/communication-store'
import {deletePushSubscription,listPushSubscriptions} from '@/lib/push-store'
export const runtime='nodejs';export const dynamic='force-dynamic'
const auth=(r:NextRequest)=>Boolean(process.env.ADMIN_PASSWORD&&r.headers.get('x-admin-password')===process.env.ADMIN_PASSWORD)
async function sendToAudience(title:string,body:string,url:string,audienceType:AudienceType,audienceDays:number){const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;const privateKey=process.env.VAPID_PRIVATE_KEY;const subject=process.env.VAPID_SUBJECT||'mailto:lebistrotducoin41220@gmail.com';if(!publicKey||!privateKey)throw new Error('Clés de notification non configurées dans Vercel.');webpush.setVapidDetails(subject,publicKey,privateKey);const members=await resolveAudience(audienceType,audienceDays);const subscriptions=[];for(const member of members){const rows=await listPushSubscriptions(member.id);subscriptions.push(...rows)}const unique=[...new Map(subscriptions.map(s=>[s.endpoint,s])).values()];let sent=0,failed=0,removed=0;const payload=JSON.stringify({title,body,url});await Promise.all(unique.map(async row=>{try{await webpush.sendNotification(row.subscription as PushSubscription,payload);sent++}catch(error){failed++;const status=typeof error==='object'&&error&&'statusCode'in error?Number(error.statusCode):0;if(status===404||status===410){await deletePushSubscription(row.endpoint);removed++}}}));return {recipientCount:members.length,totalSubscriptions:unique.length,sent,failed,removed}}
export async function GET(request:NextRequest){if(!auth(request))return NextResponse.json({error:'Accès refusé.'},{status:401});try{return NextResponse.json({campaigns:await listCampaigns(),templates:await listTemplates()})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Lecture impossible.'},{status:500})}}
export async function POST(request:NextRequest){if(!auth(request))return NextResponse.json({error:'Accès refusé.'},{status:401});try{const b=await request.json();if(b.action==='template'){const template=await saveTemplate({name:b.name,title:b.title,message:b.message,url:b.url});return NextResponse.json({ok:true,template})}if(!String(b.title||'').trim()||!String(b.message||'').trim())return NextResponse.json({error:'Titre et message obligatoires.'},{status:400});const audienceType=(b.audienceType||'all') as AudienceType;const audienceDays=Number(b.audienceDays||30);if(b.sendMode==='scheduled'){if(!b.scheduledAt)return NextResponse.json({error:'Date et heure obligatoires.'},{status:400});const campaign=await createCampaign({title:b.title,message:b.message,url:b.url,audienceType,audienceDays,scheduledAt:new Date(b.scheduledAt).toISOString(),status:'scheduled'});return NextResponse.json({ok:true,campaign})}const campaign=await createCampaign({title:b.title,message:b.message,url:b.url,audienceType,audienceDays,status:'draft'});try{const result=await sendToAudience(b.title,b.message,b.url||'/club/espace',audienceType,audienceDays);const updated=await updateCampaign(campaign.id,{status:'sent',sent_at:new Date().toISOString(),recipient_count:result.recipientCount,sent_count:result.sent,failed_count:result.failed});return NextResponse.json({ok:true,campaign:updated,...result})}catch(e){await updateCampaign(campaign.id,{status:'failed'});throw e}}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Envoi impossible.'},{status:500})}}
export async function DELETE(request:NextRequest){if(!auth(request))return NextResponse.json({error:'Accès refusé.'},{status:401});try{const {templateId}=await request.json();await deleteTemplate(templateId);return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Suppression impossible.'},{status:500})}}
